"""Create Notes table

Revision ID: 724ec98063f9
Revises: 
Create Date: 2024-01-26 14:13:14.860038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724ec98063f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
